config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :interns
  devise_for :users
  resources :pages

  #get 'pages/index'
    
  root "pages#index"

  #get 'pages/afterLogin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/intern.rb
class Intern < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

#validates :emailAdress, presence: true, length: { minimum: 10 }
validates :password, presence: true, length: { minimum: 5 }

devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :interns

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /interns
  # GET /interns.json
  def index
    @interns = Intern.all
  end

  # GET /interns/1
  # GET /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = current_user.interns.build
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns
  # POST /interns.json
  def create
    @intern = current_user.interns.build(intern_params)

      if @intern.save
        redirect_to @intern, notice = "Intern was successfully created." 
        render :show, status: :created, location: @intern 
      else
        render :new 
      end
    end

  # PATCH/PUT /interns/1
  # PATCH/PUT /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to @intern, notice: 'Intern was successfully updated.' }
        format.json { render :show, status: :ok, location: @intern }
      else
        format.html { render :edit }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1
  # DELETE /interns/1.json
  def destroy
    @intern.destroy
    respond_to do |format|
      format.html { redirect_to interns_url, notice: 'Intern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intern
      @intern = Intern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intern_params
      params.require(:intern).permit(:fullName, :otherName, :institution, :registrationNumber, :program, :year, :gender, :emailAdress, :image, :skills, :status, :college, :department, :yearOfIntern )
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def afterLogin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/interns/_form.html.erb
  <%= form_for(intern, :html => { multipart: true }) do |f| %>
  <% if intern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intern.errors.count, "error") %> prohibited this intern from being saved:</h2>

      <ul>
      <% intern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="top-content">
    <div class="inner-bg">
      <div class="container-fluid">
         <div class="row">
            <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
          
            <div class="panel-body">
         
              <div class="form-box">
                <div class="form-top">
                  <div class="form-top-left">
                    <h1>Account Registration.<span class="blinking-cursor">_</span></h1>
                      <p>Fill in the form below to get instant access:</p>
                  </div>
                </div>

                    <div class="form-bottom">
                      <form role="form" action="" method="post" class="registration-form">
                      <fieldset>
                        <legend style="color: #777272; "><p style="color: #777272; font-size:23px;">Bio-Data of Applicant</p></legend></br>
                        <div class="form-group">

                            <%= f.text_field :fullName, placeholder:"Full Name ..." %>
                        </div>
                        <div class="field">
                            <%= f.text_field :otherName, placeholder:"Other Names ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :gender, placeholder: "Gender ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :emailAdress, placeholder: "Email Address (example@something.com)" %>
                        </div>

                        <div class="field">
                            <%= f.text_field :status, placeholder: "Status" %>
                        </div>

                        <div class="field">
                            <%= f.text_field :skills, placeholder: "Skills (Area of Expertise)..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :department, placeholder: "Department..." %>
                        </div>

                        <legend><p style="color: #777272; font-size:23px;">Academic Record</p></legend></br>

                        <div class="field">
                            <%= f.text_field :institution, placeholder: "Institution (University) ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :college, placeholder: "College/Faculty ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :program, placeholder: "Program ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :registrationNumber, placeholder: "Registration Number ..." %>
                        </div>

                        <div class="field">
                            <%= f.text_field :year, placeholder: "Year Of Study (I,II,IV,) ..." %>
                        </div>
                        
                        <div class="field">
                            <%= f.text_field :year, placeholder: "Year of Internship ..." %>
                        </div>

                        <div class="field">

                            <%= f.file_field :image, class: "form-control" %>
                        </div>
                        <div class="actions">
                           <button type="submit" class="btn">Apply Now!</button>
                        </div>
                        </fieldset>
                        </form>
                    </div>
                 </div>

             </div>

             


         </div>
      </div>
  </div>
     </div>
      </div>
  </div>
  <% end %>

app/views/interns/edit.html.erb
<h1>Editing Intern</h1>

<%= render 'form', intern: @intern %>

<%= link_to 'Show', @intern %> |
<%= link_to 'Back', interns_path %>

app/views/interns/index.html.erb
   <!-- <div class="container-fluid">
      <div class="panel panel-success" style="border:2px solid #d6e9c6; margin-top:20px;">
        <div class="panel-heading">

            <h1 style="text-align:center;">Interns at Joadah & iDealinks Ltd</h1><%= link_to 'New Intern', new_intern_path, class: "btn btn-primary" %>
            <hr style="width:100%; color: #ddd; background-color: #ddd;">

             
              <p id="notice"><%= notice %></p>
          </div>
        <div class="panel-body">
          <div class="table-responsive">

        <div id="no-more-tables">
            <table class="col-md-12 table-bordered table-striped table-condensed cf">
            <thead class="cf">
              <tr>
                <tr>
                  <th>Fullname</th>
                  <th>Othername</th>
                  <th>Profilepic</th>
                  <th>Institution</th>
                  <th>Registrationnumber</th>
                  <th>Program</th>
                  <th>Year</th>
                  <th>Gender</th>
                  <th>Emailadress</th>
                 
                  <th colspan="3"> </th>
                </tr>
              </tr>
            </thead>

            <tbody>
              <% @interns.each do |intern| %>
                <tr>
                  <td><%= intern.fullName %></td>
                  <td><%= intern.otherName %></td>
                  <td><%= intern.image %></td>
                  <td><%= intern.institution %></td>
                  <td><%= intern.registrationNumber %></td>
                  <td><%= intern.program %></td>
                  <td><%= intern.year %></td>
                  <td><%= intern.gender %></td>
                  <td><%= intern.emailAdress %></td>
                  <%  if user_signed_in? && current_user.id == intern.user_id %>
                  <td><%= link_to 'Show', intern %></td>
                  <td><%= link_to 'Edit', edit_intern_path(intern) %></td>
                  <td><%= link_to 'Destroy', intern, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>

            
          </table>
        </div>
    </div>
  </div>
  </div>
</div>-->
   

<div class="container-fluid" style="margin-top:10px;">
    <div class="panel panel-success">
      <div class="panel-heading">
          <span class="panel-header-color">
            <h1 style="text-align:center;">Interns at Joadah Consults Ltd & iDeaLinks Africa Ltd</h1>
          </span>
      </div> 
      <div class="panel-body">
          <div class="container-fluid">
            <div class="row">
              <% @interns.each do |intern| %>
              <ul class="thumbnails">
                      <li class="col-md-3 col-xs-6">
                        <div class="thumbnail">
                          <div class="avatar border-white" style="height:120px;"><%= image_tag (intern.image_url.to_s), size: "50x160" %></div></br></br>
                          <div class="caption">
                            <h4><%= intern.fullName %></br><%= intern.otherName %></h4>
                            <p>Institution: &nbsp;<%= intern.institution %> </br>Program: &nbsp;<%= intern.program %> </br>Gender: &nbsp;<%= intern.gender %></p>
                            <%= link_to 'View', intern, class: "btn btn-success btn-block" %>

                          </div>
                        </div>
                      </li>
                       
                  </ul>
                  <% end %>
                </div>
                
            </div>
        </div>
    </div>
  </div>

app/views/interns/new.html.erb
<%= render 'form', intern: @intern %>

<%= link_to 'Back', interns_path %>

app/views/interns/show.html.erb
<!--<p>
  <strong>Fullname:</strong>
  <%= @intern.fullName %>
</p>

<p>
  <strong>Othername:</strong>
  <%= @intern.otherName %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @intern.institution %>
</p>

<p>
  <strong>Registrationnumber:</strong>
  <%= @intern.registrationNumber %>
</p>

<p>
  <strong>Program:</strong>
  <%= @intern.program %>
</p>

<p>
  <strong>Year:</strong>
  <%= @intern.year %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @intern.gender %>
</p>

<p>
  <strong>Emailadress:</strong>
  <%= @intern.emailAdress %>
</p>

<p>
  <strong>Profilepic:</strong>
  <%= image_tag (@intern.image_url.to_s) %>
 

</p>

<%= link_to 'Edit', edit_intern_path(@intern) %> |
<%= link_to 'Back', interns_path %>-->


 <div class="container-fluid">

          <div class="move">
           <div class="panel panel-success" style="border:2px solid #d6e9c6;">
          <div class="panel-heading">
              <h1 style="text-align:center;"> <%= @intern.fullName %>'s Profile</h1>
          </div>

          <div class="panel-body" style="background-color: #f0f0f0;">
          
            <div class="row">
              <div class="col-md-4">
              <div class="card card-user">
                <div class="image">
                  <%= image_tag("1.jpg")%>
                </div>

                <div class="content">
                    <div class="author">
                       <div class="avatar border-white" style=" height:140px;">
                        <%= image_tag (@intern.image_url.to_s) %>
                      </div>
                      <h3 class="title"><%= @intern.fullName %>  <%= @intern.otherName %><br />
                      <h4>Position: <%= @intern.status %><h4>
                      <h4>Department: <%= @intern.department %> <h4>
                      &nbsp; <p><%= @intern.institution %></p>
                      </h3>
                    </div>
                    <p class="description text-center">
                      
                      </p>

                  
              </div>
                    
              </div>
            </div>
      
            <div class="col-md-8">
              <div class="card"> 
                <div class="header1"><h4>Timeline (Profile)<hr class="pd-10"></h4>
                    <h3>About</h3>
                    <div class="row">
                      <div class="col-md-2">Name</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.fullName %></span>
                      </div>

                      <div class="col-md-2">Email</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.emailAdress %></span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Institution</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.institution %></span>
                      </div>

                      <div class="col-md-2">Phone Number</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">(+256) 773 996 470</span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Course</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.program %></span>
                      </div>

                      <div class="col-md-2">Satus</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.status %></span>
                      </div>

                    </div>


                    <div class="row">
                      <div class="col-md-2">Year</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"> III </span>
                      </div>

                      <div class="col-md-2">Interest (Area of Expertise)</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.skills %></span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Skills</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.skills %></span>
                      </div>

                      <div class="col-md-2">Year of Internship</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"><%= @intern.yearOfIntern %></span>
                      </div>
                    </div>

                    <hr class="pd-10">

                      <div class="row1">
                        <div class="col-md-4 profile-actions text-left">
                           <button type="button" class="btn btn-primary btn-sm"><i class="fa fa-envelope"></i> Send Message</button>
                        </div>
          
                         <div class="col-md-4 profile-actions text-left">
                           <button type="button" class="btn btn-primary btn-sm"><i class="fa fa-envelope"></i>Hire</button>
                        </div>
                          
                        <div class="col-md-4 profile-actions text-left">
                            <button type="button" class="btn btn-primary btn-sm"><i class="fa fa-envelope"></i>Upload</button>
                        </div>
                      </div> </br></br> </br>

                    <div class="row">
                      <div class="col-md-12">
                          <span style="color:gray; font-size:12px;"><i>3 Weeks To the end of <%= @intern.fullName %>'s Internship Period at Joadah</i></span>
                      </div>
                    </div>  
                </div>  


                </div>
                  </div>
                </div>
              </div>
              
          </div>
        </div>
      </div>
        

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("logo.png")%></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><a href="#home">Noticeboard</a></li>
          <li><%= link_to "Apply", new_intern_path %></li>
          <li><%= link_to "Internees", interns_path %></li>
          <li><a href="#tour">Training</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">  
        <%  if user_signed_in? && current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email.capitalize %>'s Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to "Edit your profile", edit_user_registration_path(current_user) %></li>
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else  %>
          <li><%= link_to "Log in",  new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path  %></li>
          </li>
        <%  end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternApp2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="container"> 
    <%=  render "layouts/messages" %>
    </div>
    <%= yield %>

  </body>
</html>

app/views/pages/afterLogin.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("logo.png")%></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#home">Internship</a></li>
          <li><a href="#home">Profile</a></li>
          <li><a href="#band">Settings</a></li>
          <li><a href="#tour" data-toggle="modal" data-target="#edit" >Sign Out</a></li>
        </ul>
      </div>
    </div>
</nav>

        <div class="container-fluid">

          <div class="move">
           <div class="panel panel-success" style="border:2px solid #d6e9c6;">
          <div class="panel-heading">
              <h1 style="text-align:center;">User Profile</h1>
          </div>

          <div class="panel-body" style="background-color: #f0f0f0;">
          
            <div class="row">
              <div class="col-md-4">
              <div class="card card-user">
                <div class="image">
                      <%= image_tag("1.jpg") %>
                </div>

                <div class="content">
                    <div class="author">
                        <%= image_tag("cico.jpg", class: "avatar border-white") %>
                      <h3 class="title">Matenga Ivan Ogarubo<br />
                      <h4>Position: Intern<h4>
                      <h4>Department: IT <h4>
                      <p><a href="#">Muni University</a></p>
                      </h3>
                    </div>
                    <p class="description text-center">
                      
                      </p>

                      <hr class="pd-10">
                  <div class="row">
                  <div class="col-sm-12 profile-actions text-left">
                  
                    <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i> Send Message</button>
                    
                     <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i>Download</button>

                     <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i>Upload</button>

                    <button type="button" class="btn1 btn-success btn-sm"><i class="fa fa-check"></i>Messages</button>

                    <span style="color:gray; font-size:12px;"><i>3 Weeks left</i></span>
                  </div>
                </div>
              </div>
                    
              </div>
            </div>
      
            <div class="col-md-8">
              <div class="card"> 
                <div class="header"><h4>Timeline (Profile)<hr class="pd-10"></h4>
                    <h3>About</h3>
                    <div class="row">
                      <div class="col-md-2">Name</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Matenga Ivan Ogarubo</span>
                      </div>

                      <div class="col-md-2">Email</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">mivan774@gmail.com</span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Institution</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Muni University</span>
                      </div>

                      <div class="col-md-2">Phone Number</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">(+256) 773 996 470</span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Course</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">BSc Information Systems</span>
                      </div>

                      <div class="col-md-2">Satus</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Intern</span>
                      </div>

                    </div>


                    <div class="row">
                      <div class="col-md-2">Year</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"> III </span>
                      </div>

                      <div class="col-md-2">Interest (Area of Expertise)</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"> UI/UX Development </span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Skills</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Autocad, Rails, Ionic, Python, php, AI </span>
                      </div>
                    </div>

                    <hr class="pd-10">
                    <h4>Profile Edit</h4>
                     <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Name" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Course" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Instituion" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Skills" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Area of Expertise" type="text">
                      </div>
                    </div>
                  </div>

                </div>
                  </div>
                </div>
              </div>
              
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>